Return no controls for devices without UpdatableProps instead of raising
Return no controls for devices without UpdatableProps instead of raising

Error while setting up ef_ble platform for button: Device has to be subclass
of UpdatableProps
TypeError: Device has to be subclass of UpdatableProps

Co-authored-by: javasoup <4626476+javasoup@users.noreply.github.com>
Co-authored-by: GnoX <gnox@gnox.dev>